version: "3"

tasks:
  default:
    desc: Run development server, watching code files for changes.
    cmds:
      - task: build-tools
      - task: generate
      - task: fmt
      - task: lint
      - task: build
      - task: run

  build:
    desc: Build .bin/doctree
    cmds:
      - mkdir -p .bin
      - go build -o .bin/doctree ./cmd/doctree
    env:
      CGO_ENABLED: 0
    sources:
      - ./**/*.go
    generates:
      - .bin/doctree

  run:
    desc: Run .bin/doctree
    cmds:
      - .bin/doctree

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test-race:
    desc: Run all tests (checking for race conditions, slow)
    cmds:
      - go test -race ./...

  generate:
    desc: Produce generated code
    cmds:
      - go generate ./...

  lint:
    desc: Lint code
    cmds:
      # Using --go=1.17 for now because of https://github.com/golangci/golangci-lint/issues/2649
      - .bin/golangci-lint run --go=1.17 ./...
    sources:
      - ./**/*.go

  fmt:
    desc: Format code
    cmds:
      - .bin/gofumpt -l -w .
    sources:
      - ./**/*.go

  build-tools:
    desc: Build tool dependencies (golangci-lint, etc.)
    cmds:
      - GOBIN="$(pwd)/.bin" go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
      - GOBIN="$(pwd)/.bin" go install mvdan.cc/gofumpt@latest
    status:
      - test -f .bin/golangci-lint
      - test -f .bin/gofumpt

  build-image:
    desc: Build sourcegraph/doctree:dev Docker image
    cmds:
      - docker build --no-cache -t sourcegraph/doctree:dev .

  run-image:
    desc: Run sourcegraph/doctree:dev Docker image
    cmds:
      - docker run -it sourcegraph/doctree:dev
